"""Micro-theory library: composable logic modules for the reasoning pipeline.

Each micro-theory provides:
- Pre-validated Prolog rules (never generated by the LLM)
- Slot definitions (what the LLM must fill)
- A builder function that assembles facts + rules + query from slots

Theories can be composed: the orchestrator merges multiple theories into
a single connected Prolog program before sending to DALI2.
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# Theory 1: Transitive Closure
# ---------------------------------------------------------------------------

def build_transitive_closure(slots: dict) -> tuple[dict | None, str]:
    """Transitive closure over a binary relation.

    Slots:
        relation  — name of the base relation (e.g. "parent")
        pairs     — list of [A, B] pairs for the base relation
        derived   — name of the transitive closure predicate (e.g. "ancestor")
        query     — {"entity": X, "target": Y} or {"entity": X, "target": "X"}
    """
    relation = slots.get("relation", "")
    pairs = slots.get("pairs", [])
    derived = slots.get("derived", "")
    query_info = slots.get("query", {})

    if not relation:
        return None, "Slot 'relation' is required (e.g. 'parent')."
    if not pairs:
        return None, "Slot 'pairs' is required (list of [A, B] pairs)."
    if not derived:
        derived = f"{relation}_closure"

    facts = []
    for pair in pairs:
        if isinstance(pair, list) and len(pair) == 2:
            facts.append({"pred": relation, "args": pair})
        elif isinstance(pair, dict):
            facts.append({"pred": relation, "args": [pair.get("from", ""), pair.get("to", "")]})

    # Transitive closure rules:
    # derived(X, Y) :- relation(X, Y).
    # derived(X, Z) :- relation(X, Y), derived(Y, Z).
    rules = [
        {
            "head": {"pred": derived, "args": ["X", "Y"]},
            "body": [{"pred": relation, "args": ["X", "Y"]}],
        },
        {
            "head": {"pred": derived, "args": ["X", "Z"]},
            "body": [
                {"pred": relation, "args": ["X", "Y"]},
                {"pred": derived, "args": ["Y", "Z"]},
            ],
        },
    ]

    # Build query
    if isinstance(query_info, dict):
        entity = query_info.get("entity", "X")
        target = query_info.get("target", "Y")
        query = {"pred": derived, "args": [entity, target]}
    elif isinstance(query_info, str):
        query = {"pred": derived, "args": [query_info, "X"]}
    else:
        query = {"pred": derived, "args": ["X", "Y"]}

    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 2: Disjunctive Exclusion
# ---------------------------------------------------------------------------

def build_disjunctive_exclusion(slots: dict) -> tuple[dict | None, str]:
    """Disjunctive reasoning: exactly one of N alternatives is true.

    Slots:
        alternatives — list of atoms that form the disjunction
        excluded     — list of atoms known to be false
        query        — atom to determine truth value of
    """
    alternatives = slots.get("alternatives", [])
    excluded = slots.get("excluded", [])
    query_atom = slots.get("query", "")

    if len(alternatives) < 2:
        return None, "Slot 'alternatives' needs at least 2 items."
    if not query_atom:
        return None, "Slot 'query' is required."

    facts = []
    for alt in alternatives:
        facts.append({"pred": "alternative", "args": [alt]})
    for exc in excluded:
        facts.append({"pred": "excluded", "args": [exc]})

    # Rules:
    # holds(X) :- alternative(X), \+ excluded(X), 
    #             forall((alternative(Y), Y \= X), excluded(Y)).
    # Simplified: if only one non-excluded alternative remains, it holds.
    rules = [
        {
            "head": {"pred": "holds", "args": ["X"]},
            "body": [
                {"pred": "alternative", "args": ["X"]},
                {"not": {"pred": "excluded", "args": ["X"]}},
                {
                    "forall": {
                        "and": [
                            {"pred": "alternative", "args": ["Y"]},
                            {"pred": "\\=", "args": ["Y", "X"]},
                        ]
                    },
                    "action": {"pred": "excluded", "args": ["Y"]},
                },
            ],
        },
    ]

    query = {"pred": "holds", "args": [query_atom]}
    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 3: Arithmetic Comparison
# ---------------------------------------------------------------------------

def build_arithmetic_compare(slots: dict) -> tuple[dict | None, str]:
    """Arithmetic comparison: find max/min among items with numeric values.

    Slots:
        values    — list of {"entity": name, "value": number}
        criterion — "max" or "min"
        query     — "best" (finds the entity matching the criterion)
    """
    values = slots.get("values", [])
    criterion = slots.get("criterion", "max")

    if not values:
        return None, "Slot 'values' is required (list of {entity, value})."
    if criterion not in ("max", "min"):
        return None, "Slot 'criterion' must be 'max' or 'min'."

    facts = []
    for v in values:
        if isinstance(v, dict):
            facts.append({"pred": "value_of", "args": [v["entity"], v["value"]]})
        elif isinstance(v, list) and len(v) == 2:
            facts.append({"pred": "value_of", "args": v})

    # Comparison operator
    if criterion == "max":
        op = "=<"  # No other Y has a value greater than X's value
    else:
        op = ">="  # No other Y has a value less than X's value

    # best(X) :- value_of(X, V), \+ (value_of(Y, W), Y \= X, W > V).  [for max]
    # best(X) :- value_of(X, V), \+ (value_of(Y, W), Y \= X, W < V).  [for min]
    inner_op = ">" if criterion == "max" else "<"
    rules = [
        {
            "head": {"pred": "best", "args": ["X"]},
            "body": [
                {"pred": "value_of", "args": ["X", "V"]},
                {
                    "not": {
                        "and": [
                            {"pred": "value_of", "args": ["Y", "W"]},
                            {"pred": "\\=", "args": ["Y", "X"]},
                            {"op": inner_op, "left": "W", "right": "V"},
                        ]
                    }
                },
            ],
        },
    ]

    query = {"pred": "best", "args": ["X"]}
    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 4: Counting / Aggregation
# ---------------------------------------------------------------------------

def build_counting(slots: dict) -> tuple[dict | None, str]:
    """Count items satisfying a condition.

    Slots:
        items      — list of {"entity": name, "properties": [prop1, ...]}
        filter     — property or predicate name to count
        query      — "count" (returns the count)
    """
    items = slots.get("items", [])
    filter_prop = slots.get("filter", "")

    if not items:
        return None, "Slot 'items' is required."
    if not filter_prop:
        return None, "Slot 'filter' is required (property to count by)."

    facts = []
    for item in items:
        if isinstance(item, dict):
            entity = item["entity"]
            facts.append({"pred": "item", "args": [entity]})
            for prop in item.get("properties", []):
                facts.append({"pred": "has_property", "args": [entity, prop]})
        elif isinstance(item, str):
            facts.append({"pred": "item", "args": [item]})

    # count_matching(N) :- findall(X, (item(X), has_property(X, filter)), Bag), length(Bag, N).
    rules = [
        {
            "head": {"pred": "count_matching", "args": ["N"]},
            "body": [
                {
                    "findall": "X",
                    "goal": {
                        "and": [
                            {"pred": "item", "args": ["X"]},
                            {"pred": "has_property", "args": ["X", filter_prop]},
                        ]
                    },
                    "bag": "Bag",
                },
                {"pred": "length", "args": ["Bag", "N"]},
            ],
        },
    ]

    query = {"pred": "count_matching", "args": ["N"]}
    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 5: Temporal Ordering
# ---------------------------------------------------------------------------

def build_temporal_ordering(slots: dict) -> tuple[dict | None, str]:
    """Temporal ordering with transitivity.

    Slots:
        events       — list of event names
        before_pairs — list of [earlier, later] pairs
        query        — {"type": "before"/"after", "event1": X, "event2": Y}
    """
    events = slots.get("events", [])
    before_pairs = slots.get("before_pairs", [])
    query_info = slots.get("query", {})

    if not before_pairs:
        return None, "Slot 'before_pairs' is required (list of [earlier, later])."

    facts = []
    for ev in events:
        facts.append({"pred": "event", "args": [ev]})
    for pair in before_pairs:
        if isinstance(pair, list) and len(pair) == 2:
            facts.append({"pred": "directly_before", "args": pair})
        elif isinstance(pair, dict):
            facts.append({"pred": "directly_before", "args": [pair["earlier"], pair["later"]]})

    # Transitive before:
    # before(X, Y) :- directly_before(X, Y).
    # before(X, Z) :- directly_before(X, Y), before(Y, Z).
    # after(X, Y) :- before(Y, X).
    rules = [
        {
            "head": {"pred": "before", "args": ["X", "Y"]},
            "body": [{"pred": "directly_before", "args": ["X", "Y"]}],
        },
        {
            "head": {"pred": "before", "args": ["X", "Z"]},
            "body": [
                {"pred": "directly_before", "args": ["X", "Y"]},
                {"pred": "before", "args": ["Y", "Z"]},
            ],
        },
        {
            "head": {"pred": "after", "args": ["X", "Y"]},
            "body": [{"pred": "before", "args": ["Y", "X"]}],
        },
    ]

    # Build query
    if isinstance(query_info, dict):
        qtype = query_info.get("type", "before")
        e1 = query_info.get("event1", "X")
        e2 = query_info.get("event2", "Y")
        query = {"pred": qtype, "args": [e1, e2]}
    else:
        query = {"pred": "before", "args": ["X", "Y"]}

    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 6: Modus Tollens
# ---------------------------------------------------------------------------

def build_modus_tollens(slots: dict) -> tuple[dict | None, str]:
    """Modus tollens: if A→B and ¬B, then ¬A.

    Slots:
        implications      — list of {"if": A, "then": B}
        negated_conclusions — list of atoms known to be FALSE
        query             — atom to determine (will check if it's negated)
    """
    implications = slots.get("implications", [])
    negated_conclusions = slots.get("negated_conclusions", [])
    query_atom = slots.get("query", "")

    if not implications:
        return None, "Slot 'implications' is required."
    if not negated_conclusions:
        return None, "Slot 'negated_conclusions' is required (atoms known false)."
    if not query_atom:
        return None, "Slot 'query' is required."

    facts = []
    for neg in negated_conclusions:
        facts.append({"pred": "known_false", "args": [neg]})

    # For each implication A→B, add: implies(a, b).
    for impl in implications:
        if isinstance(impl, dict):
            facts.append({"pred": "implies", "args": [impl["if"], impl["then"]]})
        elif isinstance(impl, list) and len(impl) == 2:
            facts.append({"pred": "implies", "args": impl})

    # Modus tollens: if A→B and B is false, then A is false
    # negated(A) :- implies(A, B), known_false(B).
    # negated(A) :- implies(A, B), negated(B).  (chain)
    rules = [
        {
            "head": {"pred": "negated", "args": ["A"]},
            "body": [
                {"pred": "implies", "args": ["A", "B"]},
                {"pred": "known_false", "args": ["B"]},
            ],
        },
        {
            "head": {"pred": "negated", "args": ["A"]},
            "body": [
                {"pred": "implies", "args": ["A", "B"]},
                {"pred": "negated", "args": ["B"]},
            ],
        },
    ]

    query = {"pred": "negated", "args": [query_atom]}
    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 7: Set Membership & Quantification
# ---------------------------------------------------------------------------

def build_set_membership(slots: dict) -> tuple[dict | None, str]:
    """Set-based reasoning with quantifiers (all/some/none).

    Slots:
        sets       — dict of {"set_name": [members...]}
        properties — list of {"entity": name, "property": prop}
        quantifier — "all", "some", "none"
        set_name   — which set to quantify over
        property   — which property to check
        query      — description of what to verify
    """
    sets = slots.get("sets", {})
    properties = slots.get("properties", [])
    quantifier = slots.get("quantifier", "all")
    set_name = slots.get("set_name", "")
    prop = slots.get("property", "")

    if not sets:
        return None, "Slot 'sets' is required."
    if not set_name or set_name not in sets:
        return None, f"Slot 'set_name' must be one of: {list(sets.keys())}."
    if not prop:
        return None, "Slot 'property' is required."

    facts = []
    for sname, members in sets.items():
        for m in members:
            facts.append({"pred": "member_of", "args": [m, sname]})
    for p in properties:
        if isinstance(p, dict):
            facts.append({"pred": "has_prop", "args": [p["entity"], p["property"]]})

    if quantifier == "all":
        # all_have(Set, Prop) :- \+ (member_of(X, Set), \+ has_prop(X, Prop)).
        rules = [
            {
                "head": {"pred": "all_have", "args": [set_name, prop]},
                "body": [
                    {
                        "not": {
                            "and": [
                                {"pred": "member_of", "args": ["X", set_name]},
                                {"not": {"pred": "has_prop", "args": ["X", prop]}},
                            ]
                        }
                    }
                ],
            },
        ]
        query = {"pred": "all_have", "args": [set_name, prop]}
    elif quantifier == "some":
        # some_have(Set, Prop) :- member_of(X, Set), has_prop(X, Prop).
        rules = [
            {
                "head": {"pred": "some_have", "args": [set_name, prop]},
                "body": [
                    {"pred": "member_of", "args": ["X", set_name]},
                    {"pred": "has_prop", "args": ["X", prop]},
                ],
            },
        ]
        query = {"pred": "some_have", "args": [set_name, prop]}
    elif quantifier == "none":
        # none_have(Set, Prop) :- \+ (member_of(X, Set), has_prop(X, Prop)).
        rules = [
            {
                "head": {"pred": "none_have", "args": [set_name, prop]},
                "body": [
                    {
                        "not": {
                            "and": [
                                {"pred": "member_of", "args": ["X", set_name]},
                                {"pred": "has_prop", "args": ["X", prop]},
                            ]
                        }
                    }
                ],
            },
        ]
        query = {"pred": "none_have", "args": [set_name, prop]}
    else:
        return None, f"Quantifier must be 'all', 'some', or 'none', got '{quantifier}'."

    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 8: Constraint Assignment (Puzzle-like)
# ---------------------------------------------------------------------------

def build_constraint_assignment(slots: dict) -> tuple[dict | None, str]:
    """Constraint satisfaction: assign properties to entities obeying constraints.

    Slots:
        entities    — list of entity names
        properties  — list of property values to assign
        constraints — list of constraints:
            {"type": "assign", "entity": E, "property": P}  (E must have P)
            {"type": "exclude", "entity": E, "property": P} (E must NOT have P)
            {"type": "same", "entity1": E1, "entity2": E2, "property": P} (share property)
            {"type": "different", "entity1": E1, "entity2": E2} (different properties)
        query       — {"entity": E} to find its assignment
    """
    entities = slots.get("entities", [])
    properties = slots.get("properties", [])
    constraints = slots.get("constraints", [])
    query_info = slots.get("query", {})

    if not entities:
        return None, "Slot 'entities' is required."
    if not properties:
        return None, "Slot 'properties' is required."

    facts = []
    for e in entities:
        facts.append({"pred": "entity", "args": [e]})
    for p in properties:
        facts.append({"pred": "property", "args": [p]})

    # Process constraints into facts
    for c in constraints:
        ctype = c.get("type", "")
        if ctype == "assign":
            facts.append({"pred": "must_have", "args": [c["entity"], c["property"]]})
        elif ctype == "exclude":
            facts.append({"pred": "cannot_have", "args": [c["entity"], c["property"]]})
        elif ctype == "different":
            facts.append({"pred": "different_from", "args": [c["entity1"], c["entity2"]]})

    # Rules for constraint solving:
    # assigned(E, P) :- must_have(E, P).
    # assigned(E, P) :- entity(E), property(P), \+ cannot_have(E, P),
    #                   \+ (must_have(E, Q), Q \= P),
    #                   \+ (must_have(F, P), F \= E).
    rules = [
        {
            "head": {"pred": "assigned", "args": ["E", "P"]},
            "body": [{"pred": "must_have", "args": ["E", "P"]}],
        },
        {
            "head": {"pred": "assigned", "args": ["E", "P"]},
            "body": [
                {"pred": "entity", "args": ["E"]},
                {"pred": "property", "args": ["P"]},
                {"not": {"pred": "cannot_have", "args": ["E", "P"]}},
                {"not": {
                    "and": [
                        {"pred": "must_have", "args": ["E", "Q"]},
                        {"pred": "\\=", "args": ["Q", "P"]},
                    ]
                }},
                {"not": {
                    "and": [
                        {"pred": "must_have", "args": ["F", "P"]},
                        {"pred": "\\=", "args": ["F", "E"]},
                    ]
                }},
            ],
        },
    ]

    # Build query
    if isinstance(query_info, dict) and "entity" in query_info:
        query = {"pred": "assigned", "args": [query_info["entity"], "X"]}
    else:
        query = {"pred": "assigned", "args": ["X", "Y"]}

    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 9: Causal Chain
# ---------------------------------------------------------------------------

def build_causal_chain(slots: dict) -> tuple[dict | None, str]:
    """Causal reasoning: causes propagate through chains.

    Slots:
        initial_causes — list of atoms that are initially true/caused
        cause_rules    — list of {"cause": A, "effect": B}
        query          — atom to check if it's caused
    """
    initial_causes = slots.get("initial_causes", [])
    cause_rules = slots.get("cause_rules", [])
    query_atom = slots.get("query", "")

    if not initial_causes:
        return None, "Slot 'initial_causes' is required."
    if not cause_rules:
        return None, "Slot 'cause_rules' is required."
    if not query_atom:
        return None, "Slot 'query' is required."

    facts = []
    for cause in initial_causes:
        facts.append({"pred": "active", "args": [cause]})
    for cr in cause_rules:
        if isinstance(cr, dict):
            facts.append({"pred": "causes", "args": [cr["cause"], cr["effect"]]})
        elif isinstance(cr, list) and len(cr) == 2:
            facts.append({"pred": "causes", "args": cr})

    # caused(X) :- active(X).
    # caused(X) :- causes(Y, X), caused(Y).
    rules = [
        {
            "head": {"pred": "caused", "args": ["X"]},
            "body": [{"pred": "active", "args": ["X"]}],
        },
        {
            "head": {"pred": "caused", "args": ["X"]},
            "body": [
                {"pred": "causes", "args": ["Y", "X"]},
                {"pred": "caused", "args": ["Y"]},
            ],
        },
    ]

    query = {"pred": "caused", "args": [query_atom]}
    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 10: Default with Exceptions
# ---------------------------------------------------------------------------

def build_default_exception(slots: dict) -> tuple[dict | None, str]:
    """Default reasoning with exceptions (non-monotonic).

    Slots:
        defaults    — list of {"class": C, "property": P} (members of C normally have P)
        exceptions  — list of {"class": C, "property": P} (members of C do NOT have P)
        instances   — list of {"entity": E, "class": C}
        query       — {"entity": E, "property": P} to check
    """
    defaults = slots.get("defaults", [])
    exceptions = slots.get("exceptions", [])
    instances = slots.get("instances", [])
    query_info = slots.get("query", {})

    if not defaults:
        return None, "Slot 'defaults' is required."
    if not instances:
        return None, "Slot 'instances' is required."

    facts = []
    for inst in instances:
        if isinstance(inst, dict):
            facts.append({"pred": "instance_of", "args": [inst["entity"], inst["class"]]})
        elif isinstance(inst, list) and len(inst) == 2:
            facts.append({"pred": "instance_of", "args": inst})

    for d in defaults:
        facts.append({"pred": "default_prop", "args": [d["class"], d["property"]]})
    for e in exceptions:
        facts.append({"pred": "exception", "args": [e["class"], e["property"]]})

    # has(E, P) :- instance_of(E, C), default_prop(C, P), \+ exception_applies(E, P).
    # exception_applies(E, P) :- instance_of(E, C), exception(C, P).
    rules = [
        {
            "head": {"pred": "has", "args": ["E", "P"]},
            "body": [
                {"pred": "instance_of", "args": ["E", "C"]},
                {"pred": "default_prop", "args": ["C", "P"]},
                {"not": {"pred": "exception_applies", "args": ["E", "P"]}},
            ],
        },
        {
            "head": {"pred": "exception_applies", "args": ["E", "P"]},
            "body": [
                {"pred": "instance_of", "args": ["E", "C"]},
                {"pred": "exception", "args": ["C", "P"]},
            ],
        },
    ]

    # Build query
    if isinstance(query_info, dict):
        entity = query_info.get("entity", "X")
        prop = query_info.get("property", "P")
        query = {"pred": "has", "args": [entity, prop]}
    else:
        query = {"pred": "has", "args": ["X", "P"]}

    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 11: Spatial Reasoning
# ---------------------------------------------------------------------------

def build_spatial_reasoning(slots: dict) -> tuple[dict | None, str]:
    """Spatial reasoning with transitivity.

    Slots:
        relations  — list of {"type": "left_of"/"right_of"/"above"/"below",
                               "entity1": A, "entity2": B}
        query      — {"type": relation_type, "entity1": A, "entity2": B}
    """
    relations = slots.get("relations", [])
    query_info = slots.get("query", {})

    if not relations:
        return None, "Slot 'relations' is required."

    facts = []
    for rel in relations:
        rtype = rel.get("type", "left_of")
        facts.append({"pred": rtype, "args": [rel["entity1"], rel["entity2"]]})

    # Transitivity + inverses for spatial relations
    rules = [
        # left_of transitive
        {"head": {"pred": "left_of", "args": ["X", "Z"]},
         "body": [{"pred": "left_of", "args": ["X", "Y"]}, {"pred": "left_of", "args": ["Y", "Z"]}]},
        # right_of is inverse of left_of
        {"head": {"pred": "right_of", "args": ["X", "Y"]},
         "body": [{"pred": "left_of", "args": ["Y", "X"]}]},
        # above transitive
        {"head": {"pred": "above", "args": ["X", "Z"]},
         "body": [{"pred": "above", "args": ["X", "Y"]}, {"pred": "above", "args": ["Y", "Z"]}]},
        # below is inverse of above
        {"head": {"pred": "below", "args": ["X", "Y"]},
         "body": [{"pred": "above", "args": ["Y", "X"]}]},
        # between: X is between A and B if A left_of X and X left_of B (or reverse)
        {"head": {"pred": "between", "args": ["X", "A", "B"]},
         "body": [{"pred": "left_of", "args": ["A", "X"]}, {"pred": "left_of", "args": ["X", "B"]}]},
    ]

    # Build query
    if isinstance(query_info, dict):
        qtype = query_info.get("type", "left_of")
        e1 = query_info.get("entity1", "X")
        e2 = query_info.get("entity2", "Y")
        query = {"pred": qtype, "args": [e1, e2]}
    else:
        query = {"pred": "left_of", "args": ["X", "Y"]}

    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Theory 12: Planning (Simple STRIPS-like)
# ---------------------------------------------------------------------------

def build_planning(slots: dict) -> tuple[dict | None, str]:
    """Simple planning: find which action achieves a goal from initial state.

    Slots:
        initial_state — list of atoms true in the initial state
        actions       — list of {"name": N, "preconditions": [...], "effects": [...]}
        goal          — list of atoms that must be true in the goal state
    """
    initial_state = slots.get("initial_state", [])
    actions = slots.get("actions", [])
    goal = slots.get("goal", [])

    if not actions:
        return None, "Slot 'actions' is required."
    if not goal:
        return None, "Slot 'goal' is required."

    facts = []
    for state_atom in initial_state:
        facts.append({"pred": "holds_in_initial", "args": [state_atom]})

    for action in actions:
        name = action["name"]
        facts.append({"pred": "action", "args": [name]})
        for pre in action.get("preconditions", []):
            facts.append({"pred": "precond", "args": [name, pre]})
        for eff in action.get("effects", []):
            facts.append({"pred": "adds", "args": [name, eff]})
        for neg in action.get("deletes", []):
            facts.append({"pred": "deletes", "args": [name, neg]})

    for g in goal:
        facts.append({"pred": "goal_cond", "args": [g]})

    # applicable(A) :- action(A), \+ (precond(A, P), \+ holds_in_initial(P)).
    # achieves_goal(A) :- applicable(A), \+ (goal_cond(G), \+ after_action(A, G)).
    # after_action(A, G) :- adds(A, G).
    # after_action(A, G) :- holds_in_initial(G), \+ deletes(A, G).
    rules = [
        {
            "head": {"pred": "applicable", "args": ["A"]},
            "body": [
                {"pred": "action", "args": ["A"]},
                {"not": {
                    "and": [
                        {"pred": "precond", "args": ["A", "P"]},
                        {"not": {"pred": "holds_in_initial", "args": ["P"]}},
                    ]
                }},
            ],
        },
        {
            "head": {"pred": "after_action", "args": ["A", "G"]},
            "body": [{"pred": "adds", "args": ["A", "G"]}],
        },
        {
            "head": {"pred": "after_action", "args": ["A", "G"]},
            "body": [
                {"pred": "holds_in_initial", "args": ["G"]},
                {"not": {"pred": "deletes", "args": ["A", "G"]}},
            ],
        },
        {
            "head": {"pred": "achieves_goal", "args": ["A"]},
            "body": [
                {"pred": "applicable", "args": ["A"]},
                {"not": {
                    "and": [
                        {"pred": "goal_cond", "args": ["G"]},
                        {"not": {"pred": "after_action", "args": ["A", "G"]}},
                    ]
                }},
            ],
        },
    ]

    query = {"pred": "achieves_goal", "args": ["X"]}
    return {"facts": facts, "rules": rules, "query": query}, ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

THEORY_BUILDERS: dict[str, callable] = {
    "transitive_closure": build_transitive_closure,
    "disjunctive_exclusion": build_disjunctive_exclusion,
    "arithmetic_compare": build_arithmetic_compare,
    "counting": build_counting,
    "temporal_ordering": build_temporal_ordering,
    "modus_tollens": build_modus_tollens,
    "set_membership": build_set_membership,
    "constraint_assignment": build_constraint_assignment,
    "causal_chain": build_causal_chain,
    "default_exception": build_default_exception,
    "spatial_reasoning": build_spatial_reasoning,
    "planning": build_planning,
}


def build_from_theory(theory_name: str, slots: dict) -> tuple[dict | None, str]:
    """Build a logic program from a micro-theory name and slot values.

    Returns (program, error). program has keys: facts, rules, query.
    """
    builder = THEORY_BUILDERS.get(theory_name)
    if builder is None:
        return None, (
            f"Unknown theory '{theory_name}'. "
            f"Available: {', '.join(THEORY_BUILDERS)}."
        )
    return builder(slots)


def compose_theories(theory_specs: list[dict]) -> tuple[dict | None, str]:
    """Compose multiple micro-theories into a single logic program.

    Each spec in theory_specs: {"theory": name, "slots": {...}}
    Facts and rules are merged; the query comes from the last theory
    (or an explicit "query" in the spec list).
    """
    all_facts = []
    all_rules = []
    final_query = None

    for spec in theory_specs:
        theory_name = spec.get("theory", "")
        slots = spec.get("slots", {})
        override_query = spec.get("query")

        program, err = build_from_theory(theory_name, slots)
        if program is None:
            return None, f"Theory '{theory_name}' failed: {err}"

        all_facts.extend(program.get("facts", []))
        all_rules.extend(program.get("rules", []))

        if override_query:
            final_query = override_query
        else:
            final_query = program.get("query")

    if not final_query:
        return None, "No query produced by any theory."

    return {"facts": all_facts, "rules": all_rules, "query": final_query}, ""


def available_theories() -> list[str]:
    """Return the list of supported theory names."""
    return list(THEORY_BUILDERS)
